### ISSUE TITLE
Permission denied: 'config.json'

### ISSUE THREAD

**Issue by zephiowl** [Spyabo/VRY--webstats#1]
After pulling the code from https://github.com/isaacKenyon/VALORANT-rank-yoinker
and running their main.py it works fine
attempting to use your modified version causes this error to appear

`The program has encountered an error. If the problem persists, please reach support with the logs found in C:\\logs
Traceback (most recent call last):
  File "C:\Users\pikac\Downloads\VALORANT-rank-yoinker-main\VALORANT-rank-yoinker-main\main.py", line 121, in <module>
    cfg = Config(log)
  File "C:\Users\pikac\Downloads\VALORANT-rank-yoinker-main\VALORANT-rank-yoinker-main\src\config.py", line 15, in __init__
    with open("config.json", "w") as file:
PermissionError: [Errno 13] Permission denied: 'config.json'
press enter to exit...`

**Comment by zephiowl** [comment]
Closed for inactivity
